export const ADD_USERNAME = 'ADD_USERNAME';

export const ADD_PLAYLIST = 'ADD_PLAYLIST';

export const REMOVE_PLAYLIST = 'REMOVE_PLAYLIST';

export const ADD_FAVORITES = 'ADD_FAVORITES';

export const REMOVE_FAVORITE = 'REMOVE_FAVORITE';

export const ADD_GOOGLEPHOTO = 'ADD_GOOGLEPHOTO';

